### PR TITLE
Clean code for MFX_BUFFER_QUEUE

### PR DESCRIPTION
**Pull request by nanazhan**
When `MFX_BUFFER_QUEUE` is enabled, `mediaskd_c2` will use a buffer queue
    implemented in `mediasdk_c2`(maybe framework doesn't support before).
    Now, we will use the buffer queue in Android media framework. Therefore,
    this part of the code is deprecated.

Tracked-On: OAM-124733

### CODE REVIEW

**Review by feijiang1 — COMMENTED** [review]
it is better add more description what's the MFX_BUFFER_QUEUE and why MFX_BUFFER_QUEUE is not needed. Maybe can get background from commit history, but if you can't find the background, it is also ok.

**Comment by nanazhan** [comment]
@feijiang1  I will add more info. For the encode part, I changed some code too, I will create a  sperate PR after more tests.

**Comment by feijiang1** [comment]
yes, the code refine can be submitted as multiple commit, every commit just focus on one specific part. Then if we found some regression, can be easier to bisect.

**Review by feijiang1 — APPROVED** [review]
LGTM

**Review by feijiang1 — APPROVED** [review]
LGTM

**Pull request merged**
